name = "InventoryRoutingLNS"
uuid = "9bd57249-2adc-458a-9ed8-13930b6156fb"
authors = ["Louis Bouvier", "Guillaume Dalle", "Axel Parmentier", "Thibaut Vidal"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
